In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
from scipy.io import loadmat

In [276]:
def copy(src_info, dst_layer, idx):
    """
    dst_layer : nn.Conv2d
    """
    layer = src_info[idx]
    kernel, bias = layer[0]['weights'][0][0]
    # in mat data  weight is w, h, c, bs
    dst_layer.weight.data.copy_(torch.from_numpy(kernel.transpose(3, 2, 1, 0)))
    dst_layer.bias.data.copy_(torch.from_numpy(bias.reshape(-1)))

In [286]:
class VGG_CNN_F(nn.Module):
    def __init__(self):
        super(VGG_CNN_F, self).__init__()
        self.conv1 = nn.Conv2d(3, 
                               64, 
                               kernel_size=11,
                               stride=4,
                               padding=0)
        self.lrn1 = nn.LocalResponseNorm(size=5,
                                         alpha=1e-4,
                                         beta=0.75,
                                         k=2)
        self.pool1 = nn.MaxPool2d(kernel_size=3,
                                  stride=2)

        self.conv2 = nn.Conv2d(64,
                               256,
                               kernel_size=5,
                               stride=1,
                               padding=2)
        self.lrn2 = nn.LocalResponseNorm(size=5,
                                         alpha=1e-4,
                                         beta=0.75,
                                         k=2)
        self.pool2 = nn.MaxPool2d(kernel_size=3,
                                  stride=2)
        self.conv3 = nn.Conv2d(256,
                               256,
                               kernel_size=3,
                               stride=1,
                               padding=1)
        self.conv4 = nn.Conv2d(256,
                               256,
                               kernel_size=3,
                               stride=1,
                               padding=1)
        self.conv5 = nn.Conv2d(256,
                               256,
                               kernel_size=3,
                               stride=1,
                               padding=1)


    def forward(self, x):
        out = self.conv1(x)
        out = self.pool1(self.lrn1(F.relu(out)))
        
        out = self.conv2(out)
        out = self.pool2(self.lrn2(F.relu(out)))

        out = F.relu(self.conv3(out))
        out = F.relu(self.conv4(out))
        out = F.relu(self.conv5(out))
        return out

    def load_mat(self, mat_path="../pretrained/imagenet-vgg-f.mat"):
        """
        idx    layer
        0       conv1
        4       conv2
        8       conv3
        10      conv4
        12      conv5
        """
        conv_idx = [0, 4, 8, 10, 12]
        conv_list = [self.conv1, self.conv2, self.conv3, self.conv4, self.conv5]
        cnn_f_weights = loadmat(mat_path)
        layers_info = cnn_f_weights['layers'][0];
        for i in range(len(conv_idx)):
            copy(layers_info, conv_list[i], conv_idx[i])

In [287]:
class VGG_CNN_M_1024(nn.Module):
    def __init__(self):
        super(VGG_CNN_M_1024, self).__init__()
        self.conv1 = nn.Conv2d(3, 
                               96, 
                               kernel_size=7,
                               stride=2,
                               padding=0)
        self.lrn1 = nn.LocalResponseNorm(size=5,
                                         alpha=1e-4,
                                         beta=0.75,
                                         k=2)
        self.pool1 = nn.MaxPool2d(kernel_size=3,
                                  stride=2)

        self.conv2 = nn.Conv2d(96,
                               256,
                               kernel_size=5,
                               stride=2,
                               padding=1)
        self.lrn2 = nn.LocalResponseNorm(size=5,
                                         alpha=1e-4,
                                         beta=0.75,
                                         k=2)
        self.pool2 = nn.MaxPool2d(kernel_size=3,
                                  stride=2)
        self.conv3 = nn.Conv2d(256,
                               512,
                               kernel_size=3,
                               stride=1,
                               padding=1)
        self.conv4 = nn.Conv2d(512,
                               512,
                               kernel_size=3,
                               stride=1,
                               padding=1)
        self.conv5 = nn.Conv2d(512,
                               512,
                               kernel_size=3,
                               stride=1,
                               padding=1)


    def forward(self, x):
        out = self.conv1(x)
        out = self.pool1(self.lrn1(F.relu(out)))
        
        out = self.conv2(out)
        out = self.pool2(self.lrn2(F.relu(out)))

        out = F.relu(self.conv3(out))
        out = F.relu(self.conv4(out))
        out = F.relu(self.conv5(out))
        return out

    def load_mat(self, mat_path="../pretrained/imagenet-vgg-m-1024.mat"):
        """
        idx    layer
        0       conv1
        4       conv2
        8       conv3
        10      conv4
        12      conv5
        """
        conv_idx = [0, 4, 8, 10, 12]
        conv_list = [self.conv1, self.conv2, self.conv3, self.conv4, self.conv5]
        cnn_f_weights = loadmat(mat_path)
        layers_info = cnn_f_weights['layers'][0];
        for i in range(len(conv_idx)):
            copy(layers_info, conv_list[i], conv_idx[i])

In [288]:
class VGG_VD_1024(nn.Module):
    def __init__(self):
        super(VGG_VD_1024, self).__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1)
        self.conv2 = nn.Conv2d(64, 64, kernel_size=3, stride=1)
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)

        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, stride=1)
        self.conv4 = nn.Conv2d(128, 128, kernel_size=3, stride=1)
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)
        
        self.conv5 = nn.Conv2d(128, 256, kernel_size=3, stride=1)
        self.conv6 = nn.Conv2d(256, 256, kernel_size=3, stride=1)
        self.conv7 = nn.Conv2d(256, 256, kernel_size=3, stride=1)
        self.pool3 = nn.MaxPool2d(kernel_size=2, stride=2)
        
        self.conv8 = nn.Conv2d(256, 512, kernel_size=3, stride=1)
        self.conv9 = nn.Conv2d(512, 512, kernel_size=3, stride=1)
        self.conv10 = nn.Conv2d(512, 512, kernel_size=3, stride=1)
        self.pool4 = nn.MaxPool2d(kernel_size=2, stride=2)
        
        self.conv11 = nn.Conv2d(512, 512, kernel_size=3, stride=1)
        self.conv12 = nn.Conv2d(512, 512, kernel_size=3, stride=1)
        self.conv13 = nn.Conv2d(512, 512, kernel_size=3, stride=1)
        
        

    def forward(self, x):
        out = F.relu(self.conv1(x))
        out = self.pool1(F.relu(self.conv2(out)))
        
        out = F.relu(self.conv3(out))
        out = self.pool2(F.relu(self.conv4(out)))
        
        out = F.relu(self.conv5(out))
        out = F.relu(self.conv6(out))
        out = self.pool3(F.relu(self.conv7(out)))
        
        out = F.relu(self.conv8(out))
        out = F.relu(self.conv9(out))
        out = self.pool4(F.relu(self.conv10(out)))
        
        out = F.relu(self.conv11(out))
        out = F.relu(self.conv12(out))
        out = F.relu(self.conv13(out))
        
        return out

    def load_mat(self, mat_path="../pretrained/imagenet-matconvnet-vgg-verydeep-16.mat"):
        conv_idx = [0, 2, 5, 7, 10, 12, 14, 17, 19, 21, 24, 26, 28]
        conv_list = [self.conv1, self.conv2, self.conv3, self.conv4, 
                     self.conv5, self.conv6, self.conv7, self.conv8,
                     self.conv9, self.conv10, self.conv11, self.conv12,
                     self.conv13]
        cnn_f_weights = loadmat(mat_path)
        layers_info = cnn_f_weights['layers'][0];
        for i in range(len(conv_idx)):
            copy(layers_info, conv_list[i], conv_idx[i])

In [56]:
#cnn_f_weights = loadmat("../region/SelectiveSearchVOC2007trainval.mat")
# layers_info = cnn_f_weights['layers'][0];
voc_07_wws = loadmat("../region/EdgeBoxesVOC2007trainval.mat")

In [57]:
voc_07_wws

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Mon May 30 18:13:07 2016',
 '__version__': '1.0',
 '__globals__': [],
 'boxScores': array([[array([[0.30461445],
        [0.29857314],
        [0.2892145 ],
        ...,
        [0.02114936],
        [0.0211394 ],
        [0.02109944]], dtype=float32),
         array([[0.23705585],
        [0.23230188],
        [0.22697584],
        ...,
        [0.01079927],
        [0.01065476],
        [0.01011905]], dtype=float32),
         array([[0.224797  ],
        [0.22350582],
        [0.22146459],
        ...,
        [0.02463008],
        [0.02462596],
        [0.02461405]], dtype=float32),
         ...,
         array([[0.2219684 ],
        [0.21137328],
        [0.21108083],
        ...,
        [0.02534551],
        [0.02531794],
        [0.02531195]], dtype=float32),
         array([[0.1734778 ],
        [0.16770221],
        [0.16218324],
        ...,
        [0.01083108],
        [0.01078979],
        [0.01051394]], 

In [47]:
voc_07_wws

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Thu Dec 22 15:13:47 2011',
 '__version__': '1.0',
 '__globals__': [],
 'boxes': array([[array([[  1,   1,   7,  64],
        [  1,   1,   8,  87],
        [  1,   1,   8,  89],
        ...,
        [364, 350, 375, 371],
        [364, 350, 375, 372],
        [364, 350, 375, 378]], dtype=uint16),
         array([[  1,   1,  38,  41],
        [  1,   1,  38,  87],
        [  1,   1,  39,  44],
        ...,
        [323, 228, 333, 247],
        [324,  62, 333,  82],
        [326, 357, 333, 376]], dtype=uint16),
         array([[  1,   1,   9,  24],
        [  1,   1,  84,  61],
        [  1,   1,  84,  71],
        ...,
        [365, 251, 375, 275],
        [367,  44, 375,  62],
        [368,  85, 375, 121]], dtype=uint16),
         ...,
         array([[  1,   1,  17,  11],
        [  1,   1,  43,  16],
        [  1,   1,  43,  22],
        ...,
        [324, 251, 333, 274],
        [328, 371, 333, 405],
        [328, 37

In [155]:
def show_layer_info(layer_info):
    if layer_info['type'][0][0] == 'conv':
        print('[conv]:')
        for i in ['size', 'pad', 'stride', 'dilate']:
            print(i + ": ")
            print(layer_info[i][0][0])
    elif layer_info['type'][0][0] == 'pool':
        print('[pool]:')
        for i in ['method', 'pool', 'stride', 'pad']:
            print(i + ": ")
            print(layer_info[i][0][0])
    else:
        print(layer_info['type'][0][0])